---
- name: Launch Docker Container
  hosts: prod
  vars:
    docker_image: "kirtantamboli/project-deployment"
    docker_tag: "latest"
    container_name: "con1"
    host_port: "80"
    container_port: "80"
  tasks:
    - name: Ensure the old container is removed
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove all Docker images (if any)
      shell: |
        images=$(docker images -q)
        if [ ! -z "$images" ]; then
          docker rmi -f $images
        fi
      ignore_errors: yes

    - name: Pull the latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run the new Docker Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        published_ports:
          - "{{ host_port }}:{{ container_port }}"
        restart_policy: always
